export const publicUserFields = [
	'_id',
	'email',
	'name',
	'jobTitle',
	'timezone',
	'emailNotifications',
	'taskNotifications',
	'weeklyDigest',
	'language',
	'avatar',
	'provider',
	'hasPassword',
	'emailVerified',
	'emailVerificationLastSentAt',
	'profileSetup',
	'createdAt',
	'updatedAt',
].join(' ')